name: Build

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache-dependency-path: package-lock.json

      - name: Cache dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --no-audit --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READER_TOKEN }}

      - name: Build
        run: npm run build
